baseurl = "/" # Hostname (and path) to the root.
title = "Lyndon Fawcett" # Site title.
theme = "hugo-coder-portfolio" # Set the theme.
languagecode = "en" # The siteâ€™s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "Lyndon" # Enable or disable Disqus.

[params] # theme parameters
    author = "Lyndon Fawcett" # Author's name.
    info = "Researcher and Developer" # Author's job title or info.
    description = "Lyndon Fawcett's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "/img/lyndon-comic-grey.png" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "" # Add footer content
    fixedbarContent = "To contact me direct: " # Add fixedbar content
    fixedbarContentAfter = "lyndonfawcett@hotmail.com" # Add fixedbar content after click

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = true
    hideCopyright = true

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/lyndon160/"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/lyndonfawcett/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/lyndon-fawcett-b8054197/"

[[menu.main]]
    name = "About"
    weight = 2
    url = "about"
